/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Film;

/**
 *
 * @author haing
 */
public class cardFilm extends javax.swing.JPanel {
    
    private String nameFilm;
    private String genre;
    private String actor;
    private String pathImage;
    private String time;
    private String introduction;
    private Film film;
    
    public cardFilm() {
        initComponents();
    }
    
    public void setData(Film film){
        this.film = film;
        pic.setImage(new javax.swing.ImageIcon(getClass().getResource(film.getPathImage())));
        filmName.setText(film.getNameFilm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filmName = new javax.swing.JLabel();
        pic = new View.PictureBox();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(200, 300));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 300));

        filmName.setBackground(new java.awt.Color(255, 255, 255));
        filmName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        filmName.setForeground(new java.awt.Color(255, 255, 255));
        filmName.setText("Film name: ");

        pic.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/lat-mat-7.jpg"))); // NOI18N
        pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filmName, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filmName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picMouseClicked
        ShowFilmInfor showfilm = new ShowFilmInfor(film);
        showfilm.setVisible(true);
        
    }//GEN-LAST:event_picMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filmName;
    private View.PictureBox pic;
    // End of variables declaration//GEN-END:variables
}
