/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ListAccount;
import Model.Film;
import javax.swing.JOptionPane;

/**
 *
 * @author haing
 */
public class ShowFilmInfor extends javax.swing.JFrame {

    private Film film;

    public ShowFilmInfor(Film film) {
        this.film = film;
        initComponents();
        setData();
    }

    public void setData() {
        pic.setImage(new javax.swing.ImageIcon(getClass().getResource(film.getPathImage())));
        genreLabel.setText(film.getGenre());
        actor.setText(film.getActor());
        time.setText(film.getTime());
        descrip.setText(film.getIntroduction());
        nameFilm.setText(film.getNameFilm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameFilm = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        actorLabel2 = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        actor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrip = new javax.swing.JTextArea();
        pic = new View.PictureBox();
        btnAddFa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1500, 770));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        nameFilm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nameFilm.setForeground(new java.awt.Color(255, 255, 255));
        nameFilm.setText("Film name");

        l1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(204, 204, 204));
        l1.setText("Genre:");

        l3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(204, 204, 204));
        l3.setText("Time:");

        l2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(204, 204, 204));
        l2.setText("Actor:");

        actorLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        actorLabel2.setForeground(new java.awt.Color(204, 204, 204));
        actorLabel2.setText("Description:");

        genreLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genreLabel.setForeground(new java.awt.Color(204, 204, 204));
        genreLabel.setText("Genre:");

        time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(204, 204, 204));
        time.setText("Genre:");

        actor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actor.setForeground(new java.awt.Color(204, 204, 204));
        actor.setText("Genre:");

        descrip.setBackground(new java.awt.Color(0, 0, 0));
        descrip.setColumns(20);
        descrip.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descrip.setRows(5);
        descrip.setBorder(null);
        jScrollPane1.setViewportView(descrip);

        btnAddFa.setBackground(new java.awt.Color(255, 204, 204));
        btnAddFa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddFa.setForeground(new java.awt.Color(0, 0, 0));
        btnAddFa.setText("Add favorite");
        btnAddFa.setBorder(null);
        btnAddFa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Exit");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l1)
                                .addGap(18, 18, 18)
                                .addComponent(genreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(l2)
                                        .addGap(22, 22, 22)
                                        .addComponent(actor, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(l3)
                                        .addGap(25, 25, 25)
                                        .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameFilm)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(actorLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(541, 541, 541)
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddFa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(nameFilm)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l1)
                            .addComponent(actorLabel2)
                            .addComponent(genreLabel))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l2)
                            .addComponent(actor))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l3)
                            .addComponent(time)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddFa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel3)))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFaActionPerformed
        if (Login.user.checkFaFilm(film)) {
            Login.user.getListFavorite().add(film);
            ListAccount.saveToFile();
            JOptionPane.showMessageDialog(null, "Successful");
        } else {
            JOptionPane.showMessageDialog(null, "Film exists");
        }

    }//GEN-LAST:event_btnAddFaActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ListFilmFrame hf = new ListFilmFrame();
        hf.setVisible(true);
        hf.pack();
        hf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actor;
    private javax.swing.JLabel actorLabel2;
    private javax.swing.JButton btnAddFa;
    private javax.swing.JTextArea descrip;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel nameFilm;
    private View.PictureBox pic;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
