/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ListAccount;
import Model.User;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author haing
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightSignUpPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        leftSignUpPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phoneNumberTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        passwordTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnSignup1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        usernameTextfield2 = new javax.swing.JTextField();
        isCus = new javax.swing.JRadioButton();
        isMana = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setMaximumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 530));
        setSize(new java.awt.Dimension(800, 500));

        rightSignUpPanel.setBackground(new java.awt.Color(122, 178, 178));
        rightSignUpPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        rightSignUpPanel.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel10.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\loginAndSignup\\icon\\welcome.png"));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/welcome.png"))); // NOI18N

        javax.swing.GroupLayout rightSignUpPanelLayout = new javax.swing.GroupLayout(rightSignUpPanel);
        rightSignUpPanel.setLayout(rightSignUpPanelLayout);
        rightSignUpPanelLayout.setHorizontalGroup(
            rightSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSignUpPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addComponent(jLabel11))
        );
        rightSignUpPanelLayout.setVerticalGroup(
            rightSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSignUpPanelLayout.createSequentialGroup()
                .addGroup(rightSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightSignUpPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel10))
                    .addGroup(rightSignUpPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel11)))
                .addGap(100, 100, 100))
        );

        leftSignUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftSignUpPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        leftSignUpPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        leftSignUpPanel.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(122, 178, 178));
        jLabel12.setText("SIGN UP");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(122, 178, 178));
        jLabel13.setText("Phone number:");

        phoneNumberTextField1.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberTextField1.setForeground(new java.awt.Color(0, 0, 0));
        phoneNumberTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 178, 178)));
        phoneNumberTextField1.setPreferredSize(new java.awt.Dimension(64, 30));
        phoneNumberTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextField1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(122, 178, 178));
        jLabel14.setText("User name:");

        passwordTextField1.setBackground(new java.awt.Color(255, 255, 255));
        passwordTextField1.setForeground(new java.awt.Color(0, 0, 0));
        passwordTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 178, 178)));
        passwordTextField1.setPreferredSize(new java.awt.Dimension(64, 30));
        passwordTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextField1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(122, 178, 178));
        jLabel15.setText("Password:");

        btnSignup1.setBackground(new java.awt.Color(122, 178, 178));
        btnSignup1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignup1.setForeground(new java.awt.Color(0, 0, 0));
        btnSignup1.setText("Sign up");
        btnSignup1.setPreferredSize(new java.awt.Dimension(80, 30));
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(122, 178, 178));
        jLabel16.setText("I have an account");

        jButton3.setBackground(new java.awt.Color(122, 178, 178));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Login");
        jButton3.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        usernameTextfield2.setBackground(new java.awt.Color(255, 255, 255));
        usernameTextfield2.setForeground(new java.awt.Color(0, 0, 0));
        usernameTextfield2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 178, 178)));
        usernameTextfield2.setPreferredSize(new java.awt.Dimension(64, 30));
        usernameTextfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextfield2ActionPerformed(evt);
            }
        });

        isCus.setText("Customer");
        isCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isCusActionPerformed(evt);
            }
        });

        isMana.setText("Manager");

        javax.swing.GroupLayout leftSignUpPanelLayout = new javax.swing.GroupLayout(leftSignUpPanel);
        leftSignUpPanel.setLayout(leftSignUpPanelLayout);
        leftSignUpPanelLayout.setHorizontalGroup(
            leftSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                .addGroup(leftSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel12))
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13))
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(phoneNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14))
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(usernameTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel15))
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSignUpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSignUpPanelLayout.createSequentialGroup()
                .addGroup(leftSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(isCus)
                        .addGap(85, 85, 85)
                        .addComponent(isMana, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        leftSignUpPanelLayout.setVerticalGroup(
            leftSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSignUpPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(phoneNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(usernameTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(6, 6, 6)
                .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(leftSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isCus)
                    .addComponent(isMana))
                .addGap(18, 18, 18)
                .addComponent(btnSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rightSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumberTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextField1ActionPerformed

    private void passwordTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextField1ActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        String phoneNumber = phoneNumberTextField1.getText();
        String username = usernameTextfield2.getText();
        String password = passwordTextField1.getText();
        if (!checkLetter_Length(phoneNumber)) {
            JOptionPane.showMessageDialog(null, "This number must have ten numbers or not contain letter");

        } else if (phoneNumber.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email can not be empty");

        } else if (username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "User can not be empty");

        } else if (password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password can not be empty");

        } else if (!isCus.isSelected() && !isMana.isSelected()) {
            JOptionPane.showMessageDialog(null, "Position can not be empty");
        } else {
            if (isCus.isSelected()) {
                if (!ListAccount.AddNewUser(username, password, phoneNumber)) {
                    JOptionPane.showMessageDialog(null, "Username exists");
                    return;
                } else {
                    ListAccount.AddNewUser(username, password, phoneNumber);
                    JOptionPane.showMessageDialog(null, "Successful");
                    return;
                }
            } else {
                if (!ListAccount.AddNewManager(username, password, phoneNumber)) {
                    JOptionPane.showMessageDialog(null, "Username exists");
                    return;
                } else {
                    ListAccount.AddNewManager(username, password, phoneNumber);
                    JOptionPane.showMessageDialog(null, "Successful");
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnSignup1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Login lf = new Login();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();    }//GEN-LAST:event_jButton3ActionPerformed

    private void usernameTextfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextfield2ActionPerformed

    private void isCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isCusActionPerformed

    public static boolean checkLetter_Length(String input) {
        if (input.length() != 10) {
            return false;
        }
        for (int i = 0; i < input.length(); i++) {
            if (!(input.charAt(i) >= '0' && input.charAt(i) <= '9')) {
                return false;
            }
        }
        return true;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup1;
    private javax.swing.JRadioButton isCus;
    private javax.swing.JRadioButton isMana;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel leftSignUpPanel;
    private javax.swing.JTextField passwordTextField1;
    private javax.swing.JTextField phoneNumberTextField1;
    private javax.swing.JPanel rightSignUpPanel;
    private javax.swing.JTextField usernameTextfield2;
    // End of variables declaration//GEN-END:variables
}
